# Generated by Django 4.2.7 on 2023-11-30 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='refresh_token',
        ),
    ]
